# Generated by Django 5.1.5 on 2025-01-19 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_animals', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewPost',
        ),
    ]
